### ISSUE TITLE
cakephp3 (bug): Pagination links  should be inactive if there is no records to display

### ISSUE THREAD

**Issue by anuid28** [cakephp/bake#141]
Pagination links (column sorting & page links)  should be inactive if there is no records in the list.
Also if there is not enough records for pagination (means there is only one page records) then pagination links {{ "previous"  and   "next"}}  should be inactive.

**Comment by markstory** [comment]
Odd the pagination links normally toggle correctly. Sorting links are not as big a problem, as you can sort no data either way and the page is still valid.

**Comment by markstory** [comment]
The generated next/prev links are customizable through [templates](http://book.cakephp.org/3.0/en/views/helpers/paginator.html#paginatorhelper-templates). The default templates always generate links as it eases integration with CSS frameworks like bootstrap and foundation.

I can change the default CSS so that the cursor does not indicate the disabled elements as clickable.

**Comment by markstory** [comment]
Closing as the default CSS will be updated in the next revision of the app skeleton as part of the 3.1 release.
