### ISSUE TITLE
Is it possibile create a bake without add?

### ISSUE THREAD

**Issue by vnt** [cakephp/bake#164]
I have created my temple for bake in plugins/MyBake/src/Template/Bake/Template/
Is there a way to create only:
- index
- edit
- view

without "add" in controller and templates?

**Comment by ionas** [comment]
If it is not in the book, you should add that AFAIK:
- For any action in your controller bake is looking for templates
- Thus if you either remove actions in your controller before backing view action templates OR if you change the controller bake templates to only render/create certain actions, then you should only have those action view templates
- Don't forget that if the view templates are not index/edit/view etc, you might need to add those templates manually (in Console somewhere, check again the book)
If this solves your issue AND if the book does not mention all that (please check), then please add add a PR to cakephp/docs so that in future peeps have an easier time.

**Comment by markstory** [comment]
No its not possible. Perhaps in the future it will be.

**Comment by josegonzalez** [comment]
@markstory you can set an event that only sets the `index`, `edit` and `view` actions when baking a controller, no?

**Comment by markstory** [comment]
@josegonzalez Yes/

**Comment by vnt** [comment]
Hello josegonzalez,
you can give me an example?

**Comment by josegonzalez** [comment]
You can do something like the following to set custom actions for your controllers:

```php
use Cake\Event\Event;
use Cake\Event\EventManager;
use Cake\Utility\Hash;
EventManager::instance()->attach(function (Event $event) {
    $view = $event->subject;
    $name = Hash::get($view->viewVars, 'name');
    $isController = strpos($event->data[0], 'Bake/Controller/controller.ctp') !== false;
    if ($isController && $name == 'Users') {
        $view->viewVars['actions'] = ['login', 'logout', 'index', 'view', 'register', 'edit', 'delete'];
    }
}, 'Bake.beforeRender');
```

**Comment by simkimsia** [comment]
@josegonzalez where would we place this code?

**Comment by ionas** [comment]
@simkimsia another way to do it is to copy the templates from vendor cakephp and make changes, 3.x example with 2 bake themes:

<img width="387" alt="screen shot 2015-11-29 at 17 38 06" src="https://cloud.githubusercontent.com/assets/106845/11458429/04fbdf0a-96c0-11e5-896e-f35cfbc60a94.png">

Enable in Boostrap:
```php
if (Configure::read('debug')) {
    Plugin::load('DebugKit', ['bootstrap' => true]);
    Plugin::load('ReadOnlyBakeTheme');
    Plugin::load('CompositePrimaryKeyTheme');
}
```

Call like:
```bin/cake bake all --theme=ReadOnlyBakeTheme --prefix Admin --force sets;```

**Comment by ionas** [comment]
As you can see some bake files and folders are even missing, those will be fetched from the cakephp core by default.

**Comment by simkimsia** [comment]
:+1: awesome job @ionas Are those plugins/themes part of this plugin?

**Comment by ionas** [comment]
No, they are custom plugins. Per theme one plugin. Maybe the option should be --theme-plugin (not sure).

**Comment by josegonzalez** [comment]
I place my bake related events in `config/events/bake_cli.php` - in a subfolder so I can see where all my events are - and include it in my `config/bootstrap_cli.php`.

**Comment by simkimsia** [comment]
@ionas can you make your bake themes available somewhere? I want to learn from what you are trying to do.

Especially if you wrote test cases for the baked templates.

@josegonzalez you mean `config/events/bake_cli` is a folder or a `.php` file?

**Comment by josegonzalez** [comment]
`config/events` is a folder containing a `bake_cli.php` file. In my apps, I try to segregate the events by some sort of "type" when they are global events - it helps keep them relatively organized.

Note the `_cli` suffix - I just borrowed the convention from the core so that I can  quickly tell if the event is global or will only affect the cli.

**Comment by ionas** [comment]
@simkimsia These bake themes are nothing special. Just baked a plugin, copied from the core and put into a plugin folder, loaded as a plugin and modified the files contents to my needs. If you want a pure copy (without tests, but they do empirically work very well) you can send me an email (email linked on GH profile) and I'll gladly zip them for you.

Intermin this could also help you but does more than what I do:
https://github.com/davidyell/CakePHP-NiceAdminBakeScripts

**Comment by simkimsia** [comment]
@ionas any chance you will put them up on github like davidyell's bake scripts?

**Comment by markstory** [comment]
Closing as the `--actions` option added in #198 will let people choose which actions they want in a controller.
