### ISSUE TITLE
<%- crashes my custom cake bake templates

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#184]
```<%-``` will crash... unless you add a space behind like ```<%- // space behind``` instead of only a new line directly following.

Why?
see for example: https://gist.github.com/ionas/946150e83780f3fa2127#file-cakephp3-bake-add-ctp-L43

**Comment by ionas** [comment]
```-%>``` always seems to crash, even if there is a space in front of it.
http://book.cakephp.org/3.0/en/bake/development.html#bake-template-syntax

**Comment by josegonzalez** [comment]
Can you gist any details about the crash?

**Comment by ionas** [comment]
Does this help you?
https://gist.github.com/ionas/3c295efb336eaa6e1dee#file-gistfile1-php-L44

**Comment by josegonzalez** [comment]
Do you maybe have alternate short tags enabled?

**Comment by josegonzalez** [comment]
We probably could handle that by adding the following regex [here](https://github.com/cakephp/bake/blob/master/src/View/BakeView.php#L56):

```php
'/\n[ \t]+<%-\n/' => "\n<%\n",
```

**Comment by ionas** [comment]
@josegonzalez I don't think I did back then (standard puphpet vagrant box with recent php 5.6.x latest stable)

**Comment by ionas** [comment]
@josegonzalez I don't think I did back then (standard puphpet vagrant box with recent php 5.6.x latest stable)

**Comment by ionas** [comment]
@josegonzalez I don't think I did back then (standard puphpet vagrant box with recent php 5.6.x latest stable)

**Comment by dereuromark** [comment]
Would that be solved with https://github.com/cakephp/bake/issues/185#issuecomment-176844479 ?

**Comment by ionas** [comment]
It would be *resolved* by utilizing another implementation. While twig really appeals to me as a *end user templating language* because you can drive it by opt-in configuration, adding another layer of complexity to something that is already advanced cakephp development... I am not so sure about that.

**Comment by dereuromark** [comment]
The layer already exists, its called *bake template*. and it uses a custom engine. I simply say use a standard one.

**Comment by josegonzalez** [comment]
@ionas do you have a PR to fix the regular expressions used for transforming the templates?

**Comment by AD7six** [comment]
> It would be resolved by utilizing an entirely different implementation.

I'm not sure if this has been missed the whole time - but the [Bake.initialize](https://github.com/cakephp/bake/blob/master/src/Shell/Task/BakeTemplateTask.php#L65-L68) event allows you to set/change the view instance - i.e. it has never been the case that you're inflexibly forced to use erb-style tags instead of whatever view implementation you want.

From the linked gist

> `<%-` will crash... unless you add a space behind <%- instead of just a new line.
> Why?

The purpose of the tag is to remove leading whitespace, it wasn't expected to be used multiline as you are doing in your examples, it's not clear why you're using these tags at all really as shown by the [test](https://github.com/cakephp/bake/blob/master/tests/test_app/App/Template/Bake/leading_whitespace.ctp) [examples](https://github.com/cakephp/bake/blob/master/tests/comparisons/BakeView/testSwallowLeadingWhitespace.php) there won't be any output at all for code like that - i.e. it should be using `<%`.

> `-%>` always seems to crash, even if there is a space in front of it.
http://book.cakephp.org/3.0/en/bake/development.html#bake-template-syntax

That tag wasn't implemented matching [how erb tags behave](https://docs.puppetlabs.com/puppet/latest/reference/lang_template_erb.html) - php already acts like this:

> With -%> — Trims the following line break.

_If_ there's nothing but a newline after the tag - so it can just be removed IMO.

**Comment by ionas** [comment]
Thank you!
