### ISSUE TITLE
Import comments from tables and fields in models

### ISSUE THREAD

**Issue by ADmad** [cakephp/bake#465]
_From @hervehobbes on October 9, 2018 8:31_

Hello,

This is a:

* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Apache, Ubuntu, Mysql

### What I'd like
When we bake models, if a table in the database has a comment, write back this comment in the Model/Table/MyTable.php script.
The same thing could be done for comments on fields

I'm not enough confortable with Cake' source code to create a PR.

_Copied from original issue: cakephp/cakephp#12631_

**Comment by ravage84** [comment]
While I see some value on this, I think it is not a really good idea.

I don't know the actual use case of @hervehobbes but we are putting comments into the database on fields and tables because we want to document them. So the DB becomes self-documenting. The proposed feature would __copy__ this documentation to the table classes, which could be good but I see two problems:

1. documentation could get out of date or ouf ot sync, which is worse than no documentation or having to fetch the DB to get the correct documentation
2. It could clutter the table code file with lots of comments which could make it huge and not necesary more readable.

Thus I tend to :-1:

**Comment by dmromanov** [comment]
Related to #442

**Comment by dereuromark** [comment]
No, the other one is about using the comments to generate specific bake templates.
This here is just to sync the comments into doc blocks, if I understand correctly.

Not sure if this should be done though.
Maybe a custom user land extension suffices here as solution.

**Comment by dereuromark** [comment]
Duplicate, closing in favor of other one.
