### ISSUE TITLE
Custom helpers for twig templates

### ISSUE THREAD

**Issue by skie** [cakephp/bake#721]
Custom helpers for twig templates could be needed when user want to add more logic to templates, which is not possible to implement in twig templates.

We can consider two options:

1. Find way to pass custom helper list in TemplateRenderer layer.
2. Allow to define custom TemplateRenderer class which loaded in all commands.

Lets discuss what is the best way to add this feature.

**Comment by ADmad** [comment]
We could add a `SimpleBakeCommand::templateRenderer()` which returns the renderer instance so people can use `$this->templateRenderer()->viewBuilder()`  in  `execute()` (or any other method) to setup the view builder.

Then `SimpleBakeCommand::bake()` would be also updated to use `templateRenderer()` instead of creating an instance itself.

**Comment by othercorey** [comment]
You can handle the bake init event to add helpers, but it doesn't let you customize the view builder before creating.
